FROM node:18 AS vite-build

# set working directory
RUN mkdir -p /app
WORKDIR /app

# cache app dependencies
COPY ./package.json ./

# install app dependencies
RUN npm i

# copy all the files to the container
COPY . .

CMD ["npm", "run", "dev"]
