version: "3.8"

services:
  dev-client:
    container_name: dev-newsletter-client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api
    volumes:
      - ./client:/app
      - /app/node_modules

  dev-api:
    container_name: dev-newsletter-api
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      MONGO_URL: "mongodb://dev-mongo/newsletter"
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - dev-mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  dev-mongo:
    container_name: dev-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
