version: "3.8"

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  client:
    container_name: newsletter-client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules

  api:
    container_name: newsletter-api
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      MONGO_URL: "mongodb://mongo/newsletter"
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
