version: "3.8"

services:
  dev-client:
    container_name: dev-newsletter-client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./client:/app
      - /app/node_modules

  dev-server:
    container_name: dev-newsletter-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - dev-mongo
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules

  dev-mongo:
    container_name: dev-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
